printWidth: 75
trailingComma: "es5"
useTabs: true
tabWidth: 4 # 4 or 2, depends on what I'm editing.
semi: true
singleQuote: true
jsxBracketSameLine: true
bracketSpacing: true
quoteProps: "as-needed"
arrowParens: "avoid"
